//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechLibrary.Api.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMenssage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMenssage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TechLibrary.Api.Language.ErrorMenssage", typeof(ErrorMenssage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome não pode ser vazio.
        /// </summary>
        public static string EXC0001 {
            get {
                return ResourceManager.GetString("EXC0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Email não pode ser vazio.
        /// </summary>
        public static string EXC0002 {
            get {
                return ResourceManager.GetString("EXC0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Password não pode ser vazio.
        /// </summary>
        public static string EXC0003 {
            get {
                return ResourceManager.GetString("EXC0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter pelo menos 6 caracteres.
        /// </summary>
        public static string EXC0004 {
            get {
                return ResourceManager.GetString("EXC0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Desconhecido.
        /// </summary>
        public static string EXC0005 {
            get {
                return ResourceManager.GetString("EXC0005", resourceCulture);
            }
        }
    }
}
